### ISSUE TITLE
Contributing writer headshots and mini-biographies

### ISSUE THREAD

**Issue by jasloe** [dramonline/soundamerican#32]
General guidelines:

**Portrait**
72 dpi
Minimum 1200 px on long edge
Provide caption/credit if possible

**Mini-biography**
Under 750 words

**Link to contributor**
Provide link to contributor's website

**Comment by jasloe** [comment]
@natewooley: I cobbled together a quick view of authors grouped by issue (in reverse order), then listed by last name.

Select "edit" at far left to edit each author node. 

I also fixed the file and directory upload permissions.

A minor editorial note: when uploading a contributor portrait, simply make the "Name" and "Alternate text" field the contributor's name. Caption should be the photographer's name, if known. Don't worry about copyright year or including the copyright symbol.  

Let me know if you have any questions.

**Comment by natewooley** [comment]
Hey Jason, 

I got through a bit of the contributor bios but it appears that I'm doing it through a page that is still showing them in alpha order. Is there a specific address to your grouping? I'm going to try and power through as many of these in the next couple days as I can. 

thanks!

**Comment by jasloe** [comment]
Are you looking at:

http://dev.soundamerican.org/admin/contributors/by-issue

??

That list is A-Z, though lists by issue in reverse chrono.

**Comment by jasloe** [comment]
If it gets to be onerous, we can forgo portraits for the time being and simply go with bio statments, e.g. https://www.theatlantic.com/ideas/archive/2019/12/senate-about-neuter-impeachment/603940/

(see bio at end of article)

**Comment by natewooley** [comment]
ahhh, okay. I just saw alpha and got confused

**Comment by natewooley** [comment]
Hey Jason,

I did the headshots and bios for Issues 21 and 20 the last couple days and opened everything today to find all that work gone. Has it been pushed and is that why I'm not seeing things? Hopefully it's backed up somewhere. Is it possible for you to check in on it to see if I did something wrong (created media and saved each time). Thanks, Nate

**Comment by jasloe** [comment]
Whoops, I accidentally swapped a database out yesterday. No problem to roll back. Let me check.

**Comment by jasloe** [comment]
Ok, just restored the db. 

Seems ok. Have a look and let me know.

Note that I yanked the articles from Issue 20. They were a mess and I'm doing them again early in the coming week. Ditto a handful of issues here in there in SA 11-20.
